version: '3.7'

services:

  client:
    container_name: client
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - api

  api:
    container_name: api
    build: ./api
    volumes:
      - './api:/app'
    ports:
      - '5000:5000'
